name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update and Install Basic Tools
      run: |
        sudo apt update
        sudo apt -y install wget unzip

    - name: Download Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip

    - name: Authenticate Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install Kali Desktop and XRDP
      run: |
        sudo apt update
        sudo apt install -y kali-desktop-xfce xrdp kali-linux-default
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure RDP User and Password
      run: |
        echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
        sudo adduser runneradmin ssl-cert
        sudo systemctl restart xrdp

    - name: Open Firewall for RDP
      run: sudo ufw allow 3389/tcp

    - name: Start Ngrok Tunnel for RDP
      run: ./ngrok tcp 3389

    - name: Display Ngrok Public URL
      run: curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"
